ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS comanda_nome VARCHAR(120);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS servido BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS gorjeta_valor NUMERIC(10,2) NOT NULL DEFAULT 0;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS motoboy_chamado BOOLEAN NOT NULL DEFAULT false;
