ALTER TABLE restaurante_config
  ADD COLUMN IF NOT EXISTS cor_fundo_clara VARCHAR(9) DEFAULT '#FDF8F0',
  ADD COLUMN IF NOT EXISTS cor_fundo_escura VARCHAR(9) DEFAULT '#1B1712',
  ADD COLUMN IF NOT EXISTS cor_botao_clara VARCHAR(9) DEFAULT '#C0392B',
  ADD COLUMN IF NOT EXISTS cor_botao_escura VARCHAR(9) DEFAULT '#E0674F',
  ADD COLUMN IF NOT EXISTS cor_texto_clara VARCHAR(9) DEFAULT '#2A2118',
  ADD COLUMN IF NOT EXISTS cor_texto_escura VARCHAR(9) DEFAULT '#F3ECE1';